### ISSUE TITLE
Anzeige bei Indikatoren drop-down hängt ab vom Browser Zoom

### ISSUE THREAD

**Issue by andhartmann** [ioer-dresden/ioer-monitor#41]
Die Anzeige im Drop Down Menue hängt von der Zoom Einstellung im Browser ab. 
90%

![grafik](https://user-images.githubusercontent.com/64139810/80702163-e8b98080-8ae0-11ea-90b2-0ea0bda545e2.png)

Bei 100% sind die Unterkategorien geöffnet.

![grafik](https://user-images.githubusercontent.com/64139810/80702492-74331180-8ae1-11ea-981e-035d3ca7667e.png)

**Comment by reinisindans** [comment]
Die Displaygrößen bei denen die Indikatorauswahlansicht sich ändert, sind jetzt besser an Content angepasst
